	use Portal_Siatkarski1;

DROP TABLE IF EXISTS Statystyki;
DROP TABLE IF EXISTS Osiagniecia;
DROP TABLE IF EXISTS Sety;
DROP TABLE IF EXISTS Reprezentacje_Mecze;
DROP TABLE IF EXISTS Mecze;
DROP TABLE IF EXISTS Zawodnicy;
DROP TABLE IF EXISTS Pozycje;

DROP TABLE IF EXISTS Trenerzy;
DROP TABLE IF EXISTS Osoby;
DROP TABLE IF EXISTS Reprezentacje;
DROP TABLE IF EXISTS Wydarzenia;
